In [2]:

import numpy as np

arr = np.array([9223311511,3393891,3373729,3474732,2284749,7272849,4847279,4847372], ndmin = 1)

print(arr.dtype)

int64


In [13]:
#Mostra la dimensió i la forma de la matriu. 

print("El nombre de dimensions de l'array és de" , arr.ndim)
print(arr)

def mostrar():
    print("La matriz es la siguiente:")
    for i in arr:
        print(i,end=" ")
    
mostrar()

El nombre de dimensions de l'array és de 1
[9223311511    3393891    3373729    3474732    2284749    7272849
    4847279    4847372]
La matriz es la siguiente:
9223311511 3393891 3373729 3474732 2284749 7272849 4847279 4847372 

In [6]:
#Valor mitjà dels valors introduits

import statistics

y =(statistics.median(arr))
print(y)

#resta la mitjana resultant de cada un dels valors
for x in arr:
    i = x-y
    print(i)

4161005.5
9219150505.5
-767114.5
-787276.5
-686273.5
-1876256.5
3111843.5
686273.5
686366.5


In [14]:
#Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, 
#i els valors màxims de cadascun dels seus eixos.

from numpy import random


quadrat = random.randint(100, size=(5, 5))

print(quadrat)

print(np.amax(quadrat))
print(np.amax(quadrat, 0))
print(np.amax(quadrat, 1))

[[ 3 46 72 30 14]
 [95 41 24 95 97]
 [63 89 19 16 48]
 [20 40 79 71 15]
 [76 35 88  8 98]]
98
[95 89 88 95 98]
[72 97 89 79 98]
